// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
    // Note: For Neon DB, ensure DATABASE_URL uses direct connection (without -pooler) for migrations
    // Use pooler connection in application code (src/lib/prisma.ts)
  },
});
